name: Test Project
on: push

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Get Repository Code
              uses: actions/checkout@v6
            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 18
            - name: Configure pnpm
              uses: pnpm/action-setup@v4
              with:
                  version: 9
            - name: Install Dependecy
              run: pnpm i
            - name: Run Tests
              run: pnpm test
